# Generated by Django 3.2.12 on 2025-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='session',
            field=models.CharField(choices=[('Forenoon', 'Forenoon'), ('Afternoon', 'Afternoon')], max_length=50),
        ),
    ]
