# Generated by Django 3.2.12 on 2025-02-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
