# Generated by Django 3.2.12 on 2025-02-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyallotment',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dutyallotment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='exam.room'),
        ),
        migrations.AlterField(
            model_name='dutyallotment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='exam.teacher'),
        ),
    ]
