# Generated by Django 3.2.12 on 2025-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Guest Lecturer', 'Guest Lecturer'), ('Junior Lecturer', 'Junior Lecturer'), ('Professor', 'Professor')], default='Assistant Professor', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
